name: Sync to public repo

on:
  push:
    branches: [main]

jobs: 
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git configuration        
        run: |
          git config --global user.name "Daniel Urchegui"
          git config --global user.email "daniel.urchegui@hotmail.com"

      - name: Delete packages/enterprise
        run: |
          rm -rf ./packages/enterprise
          rm -rf ./.github/workflows/sync-public.yml

      - name: Push to public repo
        run: |
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Nebula-Labs-SL/Systematic-Literature-Review.git
          git push public HEAD:main --force